-- AlterTable
ALTER TABLE "Employee" ADD COLUMN     "isFixedSalary" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "PayAdvice" ADD COLUMN     "bonus" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "commission" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "hoursWorked" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pension" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "reimbursement" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ytdEdTax" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ytdGross" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ytdLoanBalance" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ytdNht" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ytdNis" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ytdPaye" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ytdPension" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "PayrollRun" ADD COLUMN     "approvalNotes" TEXT,
ADD COLUMN     "approvedAt" TIMESTAMP(3),
ADD COLUMN     "approvedById" TEXT,
ADD COLUMN     "integrityHash" TEXT,
ADD COLUMN     "payrollDate" TIMESTAMP(3),
ADD COLUMN     "runNumber" INTEGER NOT NULL DEFAULT 0;

-- AddForeignKey
ALTER TABLE "PayrollRun" ADD CONSTRAINT "PayrollRun_approvedById_fkey" FOREIGN KEY ("approvedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

