ALTER TYPE "SpecimenType" ADD VALUE IF NOT EXISTS 'SPUTUM';
ALTER TYPE "SpecimenType" ADD VALUE IF NOT EXISTS 'BRONCHIAL_WASH';
ALTER TYPE "SpecimenType" ADD VALUE IF NOT EXISTS 'THYROID_FNA';
ALTER TYPE "SpecimenType" ADD VALUE IF NOT EXISTS 'LYMPH_NODE';
ALTER TYPE "SpecimenType" ADD VALUE IF NOT EXISTS 'BONE_MARROW';
ALTER TYPE "SpecimenType" ADD VALUE IF NOT EXISTS 'SKIN_SCRAPING';
