import * as fs from 'node:fs';
import * as path from 'node:path';
import { parseDicomWsiMetadata } from './dicom-wsi-parser';

/**
 * Program 5C · C2 — the parser adapter projects ONLY the C1 allowlist from a REAL binary DICOM object (a
 * small committed fixture — 64×64 matrix, 32px TILED_FULL frames, with PHI), plus a transient accession +
 * acquisition scale. It never surfaces PHI. (Fixtures are generated by testing/dicom-wsi-fixture.ts; the
 * generator's dcmjs WRITE path is exercised live in the acceptance gate under ts-node.)
 */
const fx = (n: string) => fs.readFileSync(path.join(__dirname, 'testing/__fixtures__', n));

describe('P5C-C2 parseDicomWsiMetadata (real binary DICOM fixture)', () => {
  it('extracts the C1 allowlist + transient accession + acquisition from a real WSI object', () => {
    const { metadata, accessionNumber, acquisition } = parseDicomWsiMetadata(fx('wsi-valid.dcm'));
    expect(metadata.sopClassUID).toBe('1.2.840.10008.5.1.4.1.1.77.1.6');
    expect(metadata.transferSyntaxUID).toBe('1.2.840.10008.1.2.1');
    expect(metadata.studyInstanceUID).toBe('1.2.826.0.1.3680043.2.9999.100');
    expect(metadata.seriesInstanceUID).toBe('1.2.826.0.1.3680043.2.9999.100.1');
    expect(metadata.totalPixelMatrixColumns).toBe(64);
    expect(metadata.totalPixelMatrixRows).toBe(64);
    expect(metadata.frameColumns).toBe(32);
    expect(metadata.frameRows).toBe(32);
    expect(metadata.numberOfFrames).toBe(4);
    expect(metadata.containerIdentifier).toBe('CONT-1');
    expect(accessionNumber).toBe('ACC-DICOM-1');
    expect(acquisition.objectivePower).toBe(20); // from the single OpticalPathSequence
  });

  it('never surfaces PHI (encountered in the dataset, but not mapped out)', () => {
    const parsed = parseDicomWsiMetadata(fx('wsi-valid.dcm'));
    const json = JSON.stringify(parsed);
    for (const phi of ['DOE^JANE', 'PHI-PID-123', '19700101', 'SMITH^JOHN', 'SECRET HOSPITAL', 'PatientName', 'PatientID'])
      expect(json).not.toContain(phi);
    expect(Object.keys(parsed.metadata)).not.toContain('PatientName');
  });
});
