import { IsOptional, IsString, MaxLength } from 'class-validator';

/**
 * Client-authorable fields for creating a screening batch (Phase 4.2 · C3).
 *
 * The server owns ALL authority, identity, and provenance fields — `id`,
 * `labId`, `createdById`, `status`, `batchNumber`, `assignedToId`,
 * `assignedById`, and every timestamp are set by the owner service and are
 * intentionally NOT accepted here. `batchNumber` is generated by the owner
 * (plan: owner-assigned, unique per lab); `status` always starts at the schema
 * default (`Draft`). A client cannot request an initial non-default state.
 */
export class CreateScreeningBatchDto {
  /** Optional free-text batch note. No structured/JSON payload; never clinical content. */
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  notes?: string;
}
